name: CI
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3      
        
      - name: Ruff check 
        run: uv run ruff check --output-format=github

      - name: Ruff format
        run: uv run ruff format --check
      
      - name: Test
        run: uv run pytest